### PR TITLE
Event sending Character ID for third party use

### PR DESCRIPTION
**Pull request by m3ftwz**
I needed this for a resource I'm currently developing but it's actually useful for anyone else who needs the id of the character currently spawned at selection screen.

### CODE REVIEW

**Comment by thelindat** [comment]
Seems like a very easy way to spam server events. What's the use-case?

**Comment by m3ftwz** [comment]
> Seems like a very easy way to spam server events. What's the use-case?

I'm using this to load characters' tattoos on multicharacter screen.

I thought of adding tattoos to the query that gets the character but doing so would be very specific and require a dependency so I made it like this for it to be available for any third party use.

Any better idea?

Actually, if you want to go with getting tattoos in the query I could add the tattoo column to the sql so it will return an empty string without a tattoo resource eventually.

**Comment by m3ftwz** [comment]
@thelindat better?

**Comment by thelindat** [comment]
Would be best to have examples of the event being triggered here for people to add into xnTattoos or esx_tattooshop; whatever they're using. Otherwise just go the lazy route and use the `skinchanger:modelLoaded` event and have it query the database each time.

Adding support for tattoo's is problematic because there's no set standard and it isn't supported by skinchanger or fivem-appearance - real pain in the backside.

**Comment by m3ftwz** [comment]
Decided to integrate tattoos into fivem appearance.

**Pull request closed without merging**
